### ISSUE TITLE
Start enrolling changemakers into our promotional emails

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#34]
If a changemaker decides to opt-in to our promotional emails in the action tool, we need to register them in our database as such. Currently, the `contacts` table contains various outreach datapoints. The `mailchimp_status` seems like it could be relevant, but running the following query produces lackluster results. 

```sql
SELECT DISTINCT mailchimp_status FROM contacts;

+--------------------+
| mailchimp_status   |
|--------------------|
| <null>             |
+--------------------+
```

There's a need to understand how email addresses are currently collected for promotional outreach. One possible solution is to drop the `mailchimp_status` column and replace it with the following column. 

| Column Name | Type | Modifiers | Default |
| -- | -- | -- | -- |
| promotional_enrolled| boolean | NOT_NULL | false |

**Comment by mcchang** [comment]
We currently have a Lambda that syncs Mailchimp status => Airtable and a different Lambda that syncs Airtable => Postgres. 

Here's my recommendation:
* Leave the `mailchimp_status` as it now as it may still be useful for at least analytics purposes if we fix the syncing script https://github.com/climatechangemakers/airtable_sync/blob/9b088cc0bbcbe26e83f84d4d3abe402d49c1b516/mailchimp_to_airtable/src/sync.ts#L29.  More broadly we should probably leave the `contacts` table alone since semantically it's a read-only replica of the Airtable contacts database with a few other fields from Slack and Mailchimp.
* Whenever someone opts in with their email, we can post to our api service, which can write to message to some sort of queue (maybe SQS?) that looks like 
  ```
  {
    'email': 'climate@change.com',
    'optedInAt': <timestamp>,
    ...otherMetadata
  }
  ```
  Once we have these messages written to a queue, we can add a consumer for the messages (like a Lambda) that can enroll emails using the mailchimp api (and if we'd like, persist the email somewhere for later use)
