### ISSUE TITLE
Return real LCV scores for representatives

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#5]
# Querying our database for representative LCV scores 

Objectively speaking, asking LCV to expose an API for scoring representatives is ideal. Since the frequency of LCV score updates is about every 6 months to once yearly, it's pretty low priority to have this information be totally dynamic. Therefore, we'll own these values in our database and update them as needed until we determine it's necessary for LCV to provide us this data dynamically. 

I think the big challenge here will be how we reference representatives. Representatives _do_ have a unique `bioguide`, but I'm failing to find a good source to get that ID for everyone. We're currently using the Google Civic Information API, [which doesn't currently provide a bioguide for representatives](https://groups.google.com/g/google-civicinfo-api/c/TG8b_TnPhII).

We _could_ switch back to Geocodio which provides bioguies in congressional searches. That would make this lookup easy. _However_, Geocodio is not a free API service like Google's civic API. We only get 2500 free requests per day. Ideally, Google's civic API starts providing bioguides. The linked thread above is fairly recent, but for some reason I don't have permissions to comment my interest for that information. 

Unless we have a better option, I propose that we switch back to Geocodio and structure the table as follows. 

| bioguide_id | lcv_score | score_year | 
| --------------- | -------------| ---------------- |
| M001200 | 90 | 2020 |
| M001200 | 88 | -1| 

LCV has previous scores as well as "lifetime" scores, which will be represented as `-1`. We should create a composite, unique key on `(bioguide_id, score_year)`. 

Let me know if you think anything needs to change or if this is good enough to move forward!

**Comment by kevincianfarini** [comment]
Something else to note. Geocodio is substantially slower than Google's civic API. Google requests usually take about 100ms and geocodio takes about 1100ms.

**Comment by mcchang** [comment]
Using bioguide_id seems fine for now.  I've used [Open Civic Identifier](https://opencivicdata.readthedocs.io/en/latest/ocdids.html) person ids ([example](https://github.com/openstates/people/blob/main/data/ak/legislature/Adam-Wool-094c65c5-5c69-4eee-b462-368aadcc6260.yml#L1)) in another project as a unique key for representatives if we want to look for an alternative at some point.  

It sounds like the problem we're trying to solve is how to get from an address to unique identifiers for reps. Is the LCV score dataset keyed by `bioguide_id` currently?

re: the schema specifically, I would recommend that we put lifetime scores in a different table.  A value of `-1` is not really self-describing, and having lifetime values will make any sort of aggregations on that table annoying because we'll always have to account for the lifetime values.
