### ISSUE TITLE
Import LCV scores into production database 

### ISSUE THREAD

**Issue by kevincianfarini** [climatechangemakers/climate-changemakers-act#9]
LCV scores are separated into two tables -- `lcv_year_score` and `lcv_lifetime_score`. The table definitions are as follows. 

```sql
CREATE TABLE lcv_score_year(
  bioguide_id VARCHAR NOT NULL,
  score_year INTEGER NOT NULL,
  score INTEGER NOT NULL,
  PRIMARY KEY(bioguide_id, score_year)
);

CREATE TABLE lcv_score_lifetime(
  bioguide_id VARCHAR PRIMARY KEY,
  score INTEGER NOT NULL
);
```

Importing can be done with the two CSV files I have compiled. Importing the data into their respective tables should be done as follows. 

```sql
COPY <lcv_year_score | lcv_lifetime_score> from '/path-to-csv.csv' delimiter ',' csv header;
```
Each table should be populated with 542 rows afterwards. 

References #5

**Comment by mcchang** [comment]
Some thoughts, nothing blocking.
- We could name the tables `lcv_score_year` and `lcv_score_lifetime` with a common prefix for easier discoverability
- We could add some [check constraints](https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-CHECK-CONSTRAINTS) for `score_year` (valid year) and `score` (number from 0-100) so that we can make sure we don't import bad data
- Instead of making `lcv_lifetime_score` specific to lcv scores, maybe we could rename it something like `representative_profile` or something so that we can use the table down the line to store other lifetime or non-time constrained profile attributes for representatives

**Comment by kevincianfarini** [comment]
1. Totally agree with common prefixes. 
2. Love the constraints idea. 
3. I think a more extensible approach would be to create a `representative` table that has a primary key `bioguide_id`. We can then associate lifetime scores and yearly scores to a given representative via foreign key. I do however think this is unnecessary at this stage, and we should design for this when the need arises.

**Comment by kevincianfarini** [comment]
Done!
